@startuml AliceBob
start

:fool;

note left: This is a note

:foo2;

note right
    This note is on serveral
    //lines// and can
    contain <b>HTML</b>
    ====
    * Calling the method ""foo()"" is prohibited
end note

stop
@enduml